baseURL = "https://lampseeker.github.io/"
theme = "blowfish"
defaultContentLanguage = "en"
enableRobotsTXT = true
hasCJKLanguage = true
summaryLength = 30

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
