baseURL = "https://lampseeker.github.io/"
theme = "hugo-book"
defaultContentLanguage = "ko"
enableRobotsTXT = true
hasCJKLanguage = true
summaryLength = 30
disablePathToLower = true
enableGitInfo = true

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
series = "series"

[outputs]
home = ["HTML", "RSS"]
