colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
enableImageLazyLoading = true

mainSections = ["posts", "projects"]

[header]
layout = "fixed"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "custom"
showRecent = false
showRecentItems = 20
showMoreLink = true
showMoreLinkDest = "posts"
cardView = true

[article]
showDate = true
showAuthor = true
showHero = true
heroStyle = "background"
showBreadcrumbs = true
showTableOfContents = true
showRelatedContent = true
relatedContentLimit = 6
showTaxonomies = true

[list]
showHero = true
showBreadcrumbs = true
showSummary = true
showTableOfContents = false
groupByYear = false
cardView = true
